---
title: "cleaining2020Leaders"
author: "Dave Lovell"
date: "02/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message = FALSE, warning = FALSE}
library("here")
```

## Create Architecture

```{r createArchitecture}
# Create data directory --------------------------------------------------------------
dataPlace <- here::here("data")
if(!dir.exists(dataPlace)) dir.create(dataPlace)

existingInLocal <- paste0(dataPlace, "/portmouthExistingLeaders2020Unclean.csv")
existingInODrive <- "O:\\WCC\\Learning and Development\\Research\\PROJECT - Portsmouth 2019 onwards\\Data\\unclean\\portsmouthExistingLeaders2020Unclean.csv"

# Look for existing leaders data in local dir and in O. Crash if not found.
if(file.exists(existingInLocal)) {
  writeLines("Existing Leaders Data found in data directory")
  } else if(file.exists(existingInODrive)) {
    file.copy(existingInODrive, existingInLocal)
    writeLines("Existing Leaders Data found in O Drive. Copying into data directory")
  } else {
    stop("Existing Leaders Data not found. Please place 'portsmouthExistingLeaders2020Unclean.csv` in the data directory")
  } 

  existingLeaders <- suppressMessages(readr::read_csv(existingInLocal))

  newInLocal <- paste0(dataPlace, "/portmouthNewLeaders2020Unclean.csv")
  newInODrive <- "O:\\WCC\\Learning and Development\\Research\\PROJECT - Portsmouth 2019 onwards\\Data\\unclean\\portsmouthNewLeaders2020Unclean.csv"

# Look for New leaders data in local dir and in O. Crash if not found.
if(file.exists(newInLocal)) {
  writeLines("New Leaders Data found in data directory")
  } else if(file.exists(newInODrive)) {
    file.copy(newInODrive, newInLocal)
    writeLines("new Leaders Data found in O Drive. Copying into data directory")
  } else {
    stop("new Leaders Data not found. Please place 'portsmouthNewLeaders2020Unclean.csv` in the data directory")
  } 

  newLeaders <- suppressMessages(readr::read_csv(newInLocal))
```


