---
title: "Binding 18,19 and 20 Leaders"
author: "Dave Lovell"
date: "01/06/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{r libraries, message = FALSE, warning = FALSE}
library("here")
library("dplyr")
library("forcats")
library("magrittr")
```

## Load the Data

If the Data's not there, you might do well to run `2020LeadersCleaning.Rmd`. That _should_ get the data if you're connected to `O:/` if you're not connected to `O:/` that's too bad.

```{r loadTheData}
newLeaders <- readRDS(here::here("data/leaders2020Data.rdat"))
oldLeaders <- readRDS(here::here("data/leadersResponses2018and2019.rdat"))
```

## Examine column names

What's in one but not the other?

```{r examineColNames}
### Things in old but not in new
names(oldLeaders) %>% {.[!(. %in% names(newLeaders))]}
names(newLeaders) %>% {.[!(. %in% names(oldLeaders))]}
```

## Sorting out columns

### Generate Empty Columns

Some things just need to be added as `NA`:

```{r emptyGenerate}
newLeaders[["info_deanery"]] <- NA

```

### Rename Columns

Some things just need renaming

```{r renameCols}
oldLeaders %<>% 
  rename("info_day_1" = "info_days") # There's only 1 day in 'days'
```